// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpfbctrliwysvtfzscjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZmJjdHJsaXd5c3Z0ZnpzY2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mjc4MjAsImV4cCI6MjA2MTAwMzgyMH0.-ibaJ7tUiFTAfUD2pkX5GsbhVsj4M7xlvnWkbCyjo-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);